permissions:
  contents: write

name: Convert Images to WebP

on:
  push:
    branches:
      - main
      - dev

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install sharp

      - name: Convert Images
        run: |
          find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | while read img; do
            webp_output="${img%.*}.webp"

            if [ ! -f "$webp_output" ]; then
              node -e "require('sharp')('$img').webp({ quality: 80 }).toFile('$webp_output').then(() => console.log('Converted to WebP: $img'))"
            fi

            if [ -f "$webp_output" ]; then
              rm "$img"
              echo "Removed original: $img"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated: Converted images to WebP and removed originals"
            git push
          fi
