name: Deploy Images to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure Public Directory Exists
        run: |
          mkdir -p public/resources/images
          rsync -av --ignore-missing-args ./images/ public/resources/images/

      - name: Set Custom Domain
        run: echo "resources.fossuok.org" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true  # Ensures a clean branch

      - name: Output Image URL
        run: echo "Images are now hosted at https://resources.fossuok.org/images/"
